framework:
    workflows:
        payment:
            audit_trail: true
            type: workflow
            supports:
                - App\Entity\Invoice
            marking_store:
                type: 'method'
                property: 'status'
            initial_marking: [requested]
            places:
                - requested
                - pending
                - aborted
                - failed
                - paid
                - is_refundable
                - is_refund_accepted
                - refund_allowed
                - refund_disallowed
                - refund_accepted
                - refund_rejected
                - refunded
            transitions:
                submit_request:
                    from: requested
                    to: pending
                abort:
                    from: requested
                    to: aborted
                fail:
                    from: pending
                    to: failed
                pay:
                    from: pending
                    to: paid
                submit_refund_request:
                    from: paid
                    to: [is_refundable, is_refund_accepted]
                allow_refund:
                    from: is_refundable
                    to: refund_allowed
                disallow_refund:
                    from: is_refundable
                    to: refund_disallowed
                accept_refund:
                    from: is_refund_accepted
                    to: refund_accepted
                reject_refund:
                    from: is_refund_accepted
                    to: refund_rejected
                refund:
                    from: [refund_allowed, refund_accepted]
                    to: refunded
